#!#
# Copyright (c) 2025 Hangzhou Guanwaii Technology Co,.Ltd.
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: Dockerfile
# Author: mingcheng (mingcheng@apache.org)
# File Created: 2025-06-23 22:40:57
#
# Modified By: mingcheng (mingcheng@apache.org)
# Last Modified: 2025-07-05 10:12:57
##

# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS base
LABEL MAINTAINER="mingcheng<mingcheng@apache.org>"

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# Copy package files first for better layer caching
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --prod

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
COPY . .
# If you have a build step, uncomment the next line
# RUN pnpm run build

FROM base AS runtime
COPY --from=build /app/node_modules /app/node_modules
COPY . .
# If you have a dist folder from build, copy it
# COPY --from=build /app/dist /app/dist

# Expose any required ports if needed (optional, not specific in MCP)
EXPOSE 3000

# Set environment variables for MCP server configuration
ENV BIND_PORT="3000"
ENV BIND_HOST="0.0.0.0"

# URL shortener configuration - set these via docker-compose or docker run
ENV URL_SHORTENER_API_KEY=""
ENV URL_SHORTENER_API_BASE="https://s.ee"
ENV URL_SHORTENER_DEFAULT_DOMAIN="s.ee"

# Command to run the MCP server
CMD ["pnpm", "serve"]
